---
# tasks file for docker-setup
- name: Install packages
  apt:
    name: '{{item}}'
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: apt_repository
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

- name: apt-get update
  command: apt-get update
  ignore_errors: yes

- name: Install docker-ce
  apt:
#    name: docker-ce-18.06.1.ce-3.el7.x86_64
    name: docker-ce

- name: Remove nvidia-docker1.0 volume
  shell: docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f

- name: Remove nvidia-docker package
  apt:
    name: nvidia-docker
    state: absent
    purge: yes
  ignore_errors: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: nvidia repository
  shell: distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list

- name: apt-get update
  command: apt-get update
  ignore_errors: yes

- name: Install the package nvidia-docker2
  apt:
    name: nvidia-docker2
    allow_unauthenticated: yes

- name: Init deploy path
  file:
    state:  directory
    owner:  root
    group:  root
    path:   /data/docker

- name: On ip forward
  sysctl:
    ignoreerrors: yes
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags:
    - ip_forward

- name: Mkdir /etc/docker directory
  file:
    state:  directory
    path:   /etc/docker
  tags:
    - mkdir_etc_path

- name: Copy daemon.json
  copy:
    src: gpu_daemon.json
    dest: /etc/docker/daemon.json
    mode: 0600
  tags:
    - daemon_config
  notify:
    - Restart docker-daemon
    - Enable docker

- name: Add work account to docker group
  user:
    name: work
    append: yes
    groups:
      - docker
  tags:
    - groups

- name: install docker-compose
  copy:
    src:        docker-compose
    dest:       /usr/local/bin/docker-compose
    owner:      root
    group:      root
    mode:       0755
  tags:
    - compose
