#  --
# 127.0.0.1 localhost
# 127.0.0.1 vm172-16-16-45.ksc.com
#
# --
# logstash问题：
# 172.16.16.45 localhost
# 172.16.16.45 vm172-16-16-45.ksc.com
#
# -- 改为--
# 172.16.16.45 vm172-16-16-45.ksc.com
#
# --
# 127.0.0.1 localhost
# 172.16.16.45 vm172-16-16-45.ksc.com
#

- tags:
    - hosts
  block:
    - name: Modify /etc/hosts replace 127.0.0.1
      replace:
        path:     /etc/hosts
        regexp:   '127\.0\.0\.1'
        replace:  "{{ ansible_default_ipv4.address }}"

    - name: delete localhost end
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: 'localhost$'

    # add 127.0.0.1 localhost
    - name: add 127-localhost
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1 localhost'