---
# tasks file for initialization
- tags:
  - account
  block:
    - name: add group {{init_account_group}}
      group:
        name:   '{{ init_account_group }}'
        state:  present
        gid:    '{{ init_account_gid }}'

    - name: add user {{init_account_user}}
      user:
        name:   '{{ init_account_user }}'
        shell: /bin/bash
        state:  present
        uid:    '{{ init_account_uid }}'
        group:  '{{ init_account_group }}'

    - name: set authorized key took from file
      authorized_key:
        user:       '{{ init_account_user }}'
        state:      present
        manage_dir: yes
        key:        "{{ item }}"
      with_file: '{{init_ssh_keys}}'

    - name: grant sudo privilege to {{init_account_user}}
      lineinfile:
        path:           /etc/sudoers
        state:          present
        insertafter:    '.*ALL=\(ALL\).*'
        line:           '{{init_account_user}}    ALL=(ALL)       NOPASSWD:ALL'
        validate:       'visudo -cf %s'

    - name: cancel requiretty when sudo
      lineinfile:
        path:           /etc/sudoers
        state:          present
        regexp:         'requiretty'
        line:           '#Defaults    requiretty'
